### PR TITLE
RD-2427 related terms -> similar terms

### PR DESCRIPTION
**Pull request by iredpath**

### CODE REVIEW

**Comment by dscorbett** [comment]
This PR renames public API items present in the latest release. That is a breaking change and the new version should have been called 3.0.0; however, since this is such a small change, I don’t think it warrants a major version bump. I recommend the following:

* Restore and deprecate any deleted items that were present in 2.5.1.
* Alias them to the preferred names.
* Update the release notes to tell users not to use 2.6.0.
* Merge the PR.
* Release version 2.7.0.

**Comment by dscorbett** [comment]
Ugh. I guess that’s okay. It’s not the first time we’ve ignored semver.

If they were not usable, why were they ever released?

**Comment by iredpath** [comment]
at the time of their release, we had come to the agreement that the endpoint would be referred to as `related terms`.  We've since changed this to be `similar terms` to more closely align with the actual path of the endpoint.

**Comment by dscorbett** [comment]
I see. Well, next time we add something to the ADM that depends on a future endpoint, let’s keep it on its own branch, and not release it till we know this won’t happen again.

**Comment by Katsuya-Tomioka** [comment]
Looks good to me. 2.5.2 to address the name change. Merging.

**Comment by iredpath** [comment]
to clarify, version 2.6.0 was dropped from staging and never publicly released.  version 2.5.2 is the latest available version

**Pull request merged**
