### PR TITLE
ETROG-3636: Expose secondary parts of speech

### PR DESCRIPTION
**Pull request by juliencherry**

### CODE REVIEW

**Review by dscorbett — CHANGES_REQUESTED** [review]
The subclasses of `MorphoAnalysis` need extra constructors for backwards compatibility, like you added for `MorphoAnalysis` itself.

**Comment by dscorbett** [comment]
The classes like `MorphoAnalysisMixin` do not list `secondaryPartOfSpeech`. Does it matter? Note that they also don’t list `tagSet`, the other relatively new field. I do not know the ramifications of these omissions.

**Comment by juliencherry** [comment]
It does seem that `tagSet` should have been included in `MorphoAnalysisMixin`, so I think that both fields should be included for consistency. We can then determine whether the omission had caused any problems in downstream projects.

**Comment by juliencherry** [comment]
It does seem that `tagSet` should have been included in `MorphoAnalysisMixin`, so I think that both fields should be included for consistency.

**Review by dscorbett — APPROVED** [review]

**Comment by dscorbett** [comment]
The (de)serialization unit tests prove that the omission of `tagSet` and `secondaryPartOfSpeech` from the mixin does not matter.

**Pull request merged**
